### ISSUE TITLE
Failed to load the linter-less package

### ISSUE THREAD

**Issue by Horn-Main** [AtomLinter/linter-less#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [linter-less](https://github.com/AtomLinter/linter-less) package, v2.2.0

### Stack Trace

Failed to load the linter-less package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Сергей\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Сергей\.atom\packages\linter-less\lib\init.coffee:5:15)
    at Object.<anonymous> (C:\Users\Сергей\.atom\packages\linter-less\lib\init.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Сергей\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Сергей\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
    at C:\Users\Сергей\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
    at Package.module.exports.Package.measure (C:\Users\Сергей\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
```

### Commands

```
     -2:25.6.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:17.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:41 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:26 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:24 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.11
linter-less, v2.2.0

# Dev
No dev packages
```

**Comment by josa42** [comment]
@Horn-Main How did you install the package?

**Comment by Arcanemagus** [comment]
This is almost certainly another instance of https://github.com/atom/atom/issues/8891 due to having non-ascii characters in your user profile path. There unfortunately is nothing that can be done until Atom releases the next version.

**Comment by Arcanemagus** [comment]
@Horn-Main 

[Atom v1.2.0-beta0](https://github.com/atom/atom/releases/tag/v1.2.0-beta0) has been released as a beta, and it includes the updated Electron version that reportedly fixes this issue. If you don't want to wait until v1.2.0 is officially released you can install this preview now.
